Gharkhoji/Gharkhoji/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pages/', include('pages.urls', namespace='pages')),
    path('listing/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gharkhoji/accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

]

Gharkhoji/listings/urls.py
from django.urls import path, include
from . import views

app_name = 'listings'

urlpatterns = [
    path('home/', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search/', views.search, name='search'),

]

Gharkhoji/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('about/', views.about, name='about'),


]

Gharkhoji/templates/partials/_alerts.html
{% if messages %}
    {% for message in messages %}
        <div id="message" class="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">
                    &times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error:
                    {% else %}
                        {{ message.tags | title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

Gharkhoji/templates/partials/_footer.html
<!-- Footer -->
<footer id="main-footer" class="py-4 bg-primary text-white text-center">
    Copyright &copy;
    <span class="year"></span> GharKhoji
</footer>

Gharkhoji/templates/partials/_navbar.html
{% load static %}
{% url 'pages:index' as index_url %}
{% url 'pages:about' as about_url %}
{% url 'listings:listings' as listings_url %}
{% url 'accounts:register' as register_url %}
{% url 'accounts:login' as login_url %}
{% url 'accounts:logout' as logout_url %}
{% url 'accounts:dashboard' as dashboard_url %}

<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
        <a class="navbar-brand" href="index.html">
            <img src="{% static 'img/logo.png' %}" height="50" width="80" class="logo" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav">
                <li class="nav-item {% if request.path ==  index_url %} active {% endif %} mr-3">
                    <a class="nav-link" href="{{ index_url }}">Home</a>
                </li>
                <li class="nav-item {% if request.path ==  about_url %} active {% endif %} mr-3">
                    <a class="nav-link" href="{{ about_url }}">About</a>
                </li>
                <li class="nav-item {% if request.path ==  listings_url %} active {% endif %} mr-3"">
                    <a class="nav-link" href="{{ listings_url }}">Featured Listings</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item {% if request.path ==  dashboard_url %} active {% endif %}  mr-3">
                        <a class="nav-link" href="{{ dashboard_url }}">
                            Welcome {{ user.username }}(Dashboard)</a>
                    </li>
                    <li class="nav-item mr-3">
                        <a href="javascript:{document.getElementById('logout').submit()}" class="nav-link">
                            <i class="fas fa-sign-out-alt"></i> Logout
                        </a>
                        <form action="{{ logout_url }}" method="POST" id="logout">
                            {% csrf_token %}
                            <input type="hidden">
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path ==  register_url %} active {% endif %}  mr-3">
                        <a class="nav-link" href="{{ register_url }}">
                            <i class="fas fa-user-plus"></i> Register</a>
                    </li>
                    <li class="nav-item {% if request.path ==  login_url %} active {% endif %}   mr-3">
                        <a class="nav-link" href="{{ login_url }}">
                            <i class="fas fa-sign-in-alt"></i>

                            Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

Gharkhoji/templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <i class="fas fa-phone"></i> (+977)-9845123710
            </div>
            <div class="col-md-4">
                <i class="fas fa-envelope-open"></i> contact@gharkhoji.co
            </div>
            <div class="col-md-4">
                <div class="social text-right">
                    <a href="#">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-facebook"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-linkedin"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="#">
                        <i class="fab fa-pinterest"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>