Gharkhoji/Gharkhoji/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('pages/', include('pages.urls', namespace='pages')),
    path('listing/', include('listings.urls', namespace='listings')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('contacts/', include('contacts.urls', namespace='contacts')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Gharkhoji/contacts/urls.py
from django.urls import path
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact, name='contact'),

]

Gharkhoji/listings/urls.py
from django.urls import path, include
from . import views

app_name = 'listings'

urlpatterns = [
    path('home/', views.index, name='listings'),
    path('<int:listing_id>', views.listing, name='listing'),
    path('search/', views.search, name='search'),

]

Gharkhoji/pages/urls.py
from django.urls import path, include
from . import views

app_name = 'pages'

urlpatterns = [
    path('home/', views.index, name='index'),
    path('about/', views.about, name='about'),


]

Gharkhoji/listings/models.py
from django.db import models
from datetime import datetime
from realtors.models import Realtor


class Listing(models.Model):
    realtor = models.ForeignKey(Realtor, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    bedrooms = models.IntegerField()
    bathrooms = models.IntegerField()
    kitchen = models.IntegerField()
    house_area = models.DecimalField(max_digits=7, decimal_places=2)
    land_area = models.DecimalField(max_digits=7, decimal_places=2)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

Gharkhoji/listings/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from .choices import price_choices, bedroom_choices

from .models import Listing


def index(request):
    listings = Listing.objects.order_by('-list_date').filter(is_published=True)

    paginator = Paginator(listings, 6)
    page = request.GET.get('page')
    paged_listings = paginator.get_page(page)

    context = {
        'listings': paged_listings,
    }
    return render(request, 'listings/listings.html', context)


def listing(request, listing_id):
    listing = get_object_or_404(Listing, id=listing_id)


    context = {
        'listing': listing
    }
    return render(request, 'listings/listing.html', context)


def search(request):
    queryset_list = Listing.objects.order_by('-list_date')

    # #keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']

        if keywords:
            queryset_list = queryset_list.filter(description__icontains=keywords)
    # city
    if 'city' in request.GET:
        city = request.GET['city']
        if city:
            queryset_list = queryset_list.filter(city__iexact=city)

    # bedrooms
    if 'bedrooms' in request.GET:
        bedrooms = request.GET['bedrooms']
        if bedrooms:
            queryset_list = queryset_list.filter(bedrooms__lte=bedrooms)
    # price
    if 'price' in request.GET:
        price = request.GET['price']
        if price:
            queryset_list = queryset_list.filter(price__lte=price)
    context = {
        'price_choices': price_choices,
        'bedroom_choices': bedroom_choices,
        'listings': queryset_list,
        'values': request.GET,
    }
    return render(request, 'listings/search.html', context)

Gharkhoji/templates/listings/listing.html
{% extends 'base.html' %}



{% load humanize %}

{% block title %}{{ listing.title }}{% endblock %}

{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">{{ listing.title }}</h1>
          <p class="lead">
            <i class="fas fa-map-marker"></i> {{ listing.address }}, {{ listing.city }}</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="{% url 'listings:listings' %}">Listings</a>
          </li>
          <li class="breadcrumb-item active">{{ listing.title }}</li>
        </ol>
      </nav>
    </div>
  </section>
<br>
  <!-- Alerts -->
  {% include 'partials/_alerts.html' %}
  <!-- Listing -->
  <section id="listing" class="py-4">
    <div class="container">
      <a href="{% url 'listings:listings' %}" class="btn btn-light mb-4">Back To Listings</a>
      <div class="row">
        <div class="col-md-9">
          <!-- Home Main Image -->
          <img src="{{ listing.photo_main.url }}" alt="" class="img-main img-fluid mb-3">
          <!-- Thumbnails -->
          <div class="row mb-5 thumbs">
            {% if listing.photo_1 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_1.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_1.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_2 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_2.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_2.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_3 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_3.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_3.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_4 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_4.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_4.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_5 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_5.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_5.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
            {% if listing.photo_6 %}
            <div class="col-md-2">
              <a href="{{ listing.photo_6.url }}" data-lightbox="home-images">
                <img src="{{ listing.photo_6.url }}" alt="" class="img-fluid">
              </a>
            </div>
            {% endif %}
          </div>
          <!-- Fields -->
          <div class="row mb-5 fields">
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-money-bill-alt"></i> Asking Price:
                  <span class="float-right">Rs.{{ listing.price | intcomma }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Bedrooms:
                  <span class="float-right">{{ listing.bedrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bath"></i> Bathrooms:
                  <span class="float-right">{{ listing.bathrooms }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-car"></i> kitchen:
                  <span class="float-right">{{ listing.kitchen }}
                  </span>
                </li>
              </ul>
            </div>
            <div class="col-md-6">
              <ul class="list-group list-group-flush">
                <li class="list-group-item text-secondary">
                  <i class="fas fa-th-large"></i> Square Feet:
                  <span class="float-right">{{ listing.house_area }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-square"></i> Land Area:
                  <span class="float-right">{{ listing.land_area }}
                  </span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-calendar"></i> Listing Date:
                  <span class="float-right">{{ listing.list_date }}</span>
                </li>
                <li class="list-group-item text-secondary">
                  <i class="fas fa-bed"></i> Realtor:
                  <span class="float-right">{{ listing.realtor.name }}
                  </span>
                </li>


              </ul>
            </div>
          </div>

          <!-- Description -->
          <div class="row mb-5">
            <div class="col-md-12">
                {{ listing.description }}
            </div>
          </div>
        </div>
        <div class="col-md-3">
          <div class="card mb-3">
            <img class="card-img-top" src="{{ listing.realtor.photo.url }}" alt="Seller of the month">
            <div class="card-body">
              <h5 class="card-title">Property Realtor</h5>
              <h6 class="text-secondary">{{ listing.realtor.name }}</h6>
              <h6 class="text-secondary">Contact:<small>{{ listing.realtor.phone }}</small></h6>
            </div>
          </div>
          <button class="btn-primary btn-block btn-lg" data-toggle="modal" data-target="#inquiryModal">Make An Inquiry</button>
        </div>
      </div>
    </div>
  </section>

  <!-- Inquiry Modal -->
  <div class="modal fade" id="inquiryModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="inquiryModalLabel">Make An Inquiry</h5>
          <button type="button" class="close" data-dismiss="modal">
            <span>&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form action="{% url 'contacts:contact' %}" method="POST">{% csrf_token %}
                {% if user.is_authenticated %}
                    <input type="hidden" name="user_id" value="{{ user.id }}">
                {% else %}
                    <input type="hidden" name="user_id" value="0">
                {% endif %}
                <input type="hidden" name="realtor_email" value="{{ listing.realtor.email }}">
                <input type="hidden" name="listing_id" value="{{ listing.id }}">

                <div class="form-group">
                    <label for="property_name" class="col-form-label">Property:</label>
                    <input type="text" name="listing" class="form-control" value="{{ listing.title }}">
                </div>
                <div class="form-group">
                    <label for="name" class="col-form-label">Name:</label>
                    <input type="text" name="name" class="form-control" {% if user.is_authenticated %}
                           value="{{ user.first_name }} {{ user.last_name }}" {% endif %} required>
                </div>
                <div class="form-group">
                    <label for="email" class="col-form-label">Email:</label>
                    <input type="email" name="email" class="form-control" {% if user.is_authenticated %}
                           value="{{ user.email }}" {% endif %} required>
                </div>
                <div class="form-group">
                    <label for="phone" class="col-form-label">Phone:</label>
                    <input type="text" name="phone" class="form-control">
                </div>
                <div class="form-group">
                    <label for="message" class="col-form-label">Message:</label>
                    <textarea name="message" class="form-control"></textarea>
                </div>
                <hr>
                <input type="submit" value="Send" class="btn btn-block btn-secondary">
            </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

Gharkhoji/templates/listings/listings.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}Browse Property Listings{% endblock %}
{% block content %}
  <section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">Browse Our Properties</h1>
          <p class="lead">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sunt, pariatur!</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'pages:index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Browse Listings</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
  <section id="listings" class="py-4">
    <div class="container">
      <div class="row">
        {% if listings %}
            {% for listing in listings %}
                <div class="col-md-6 col-lg-4 mb-4">
                    <div class="card listing-preview">
                        <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                        <div class="card-img-overlay">
                            <h2>
                                <span class="badge badge-secondary text-white">Rs.{{ listing.price | intcomma }}</span>
                            </h2>
                        </div>
                        <div class="card-body">
                            <div class="listing-heading text-center">
                                <h4 class="text-primary">{{ listing.title }}</h4>
                                <p>
                                    <i class="fas fa-map-marker text-secondary"></i>
                                    {{ listing.address }}, {{ listing.city }}
                                </p>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-th-large"></i> Sqft: {{ listing.house_area }}</div>
                                <div class="col-6">
                                    <i class="fas fa-car"></i> kitchens: {{ listing.kitchen }}</div>
                            </div>
                            <div class="row py-2 text-secondary">
                                <div class="col-6">
                                    <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                                <div class="col-6">
                                    <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                            </div>
                            <hr>
                            <div class="row py-2 text-secondary">
                                <div class="col-12">
                                    <i class="fas fa-user"></i>{{ listing.realtor.name }}</div>
                            </div>
                            <div class="row text-secondary pb-2">
                                <div class="col-6">
                                    <i class="fas fa-clock"></i> {{ listing.list_date | timesince}}</div>
                            </div>
                            <hr>
                            <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="col-md-12">
                <p>No Listings available</p>
            </div>
        {% endif %}


      </div>

        <div class="row">
            <div class="col-md-12">
                {% if listings.has_other_pages %}
                    <ul class="pagination">
                        {% if listings.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ listings.previous_page_number }}" class="page-link">&laquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">&laquo;</a>
                            </li>
                        {% endif %}


                        {% for i in listings.paginator.page_range %}
                            {% if listings.number == i %}
                                <li class="page-item active">
                                    <a class="page-link">{{ i }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                        {% if listings.has_next %}
                            <li class="page-item">
                                <a href="?page={{ listings.next_page_number }}" class="page-link">&raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link">&raquo;</a>
                            </li>

                        {% endif %}
                    </ul>
            {% endif %}
            </div>
        </div>
    </div>
  </section>
{% endblock %}

Gharkhoji/templates/listings/search.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}Search Results{% endblock %}
{% block content %}
 <section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <form action="{% url 'listings:search' %}">
            <!-- Form Row 1 -->
            <div class="form-row">
              <div class="col-md-4 mb-3">
                <label class="sr-only">Keywords</label>
                <input type="text" name="keywords" class="form-control" placeholder="Keyword" value="{{ values.keywords }}">
              </div>

              <div class="col-md-4 mb-3">
                <label class="sr-only">City</label>
                <input type="text" name="city" class="form-control" placeholder="City" value="{{ values.city }}">
              </div>

{#              <div class="col-md-4 mb-3">#}
{#                <label class="sr-only">State</label>#}
{#                <select name="state" class="form-control">#}
{#                  <option selected="true" disabled="disabled">State (All)</option>#}
{#                  <option value="AL">Alabama</option>#}
{#                  <option value="AK">Alaska</option>#}
{#                  <option value="AZ">Arizona</option>#}
{#                  <option value="AR">Arkansas</option>#}
{#                  <option value="CA">California</option>#}
{#                  <option value="CO">Colorado</option>#}
{#                  <option value="CT">Connecticut</option>#}
{#                  <option value="DE">Delaware</option>#}
{#                  <option value="DC">District Of Columbia</option>#}
{#                  <option value="FL">Florida</option>#}
{#                  <option value="GA">Georgia</option>#}
{#                  <option value="HI">Hawaii</option>#}
{#                  <option value="ID">Idaho</option>#}
{#                  <option value="IL">Illinois</option>#}
{#                  <option value="IN">Indiana</option>#}
{#                  <option value="IA">Iowa</option>#}
{#                  <option value="KS">Kansas</option>#}
{#                  <option value="KY">Kentucky</option>#}
{#                  <option value="LA">Louisiana</option>#}
{#                  <option value="ME">Maine</option>#}
{#                  <option value="MD">Maryland</option>#}
{#                  <option value="MA">Massachusetts</option>#}
{#                  <option value="MI">Michigan</option>#}
{#                  <option value="MN">Minnesota</option>#}
{#                  <option value="MS">Mississippi</option>#}
{#                  <option value="MO">Missouri</option>#}
{#                  <option value="MT">Montana</option>#}
{#                  <option value="NE">Nebraska</option>#}
{#                  <option value="NV">Nevada</option>#}
{#                  <option value="NH">New Hampshire</option>#}
{#                  <option value="NJ">New Jersey</option>#}
{#                  <option value="NM">New Mexico</option>#}
{#                  <option value="NY">New York</option>#}
{#                  <option value="NC">North Carolina</option>#}
{#                  <option value="ND">North Dakota</option>#}
{#                  <option value="OH">Ohio</option>#}
{#                  <option value="OK">Oklahoma</option>#}
{#                  <option value="OR">Oregon</option>#}
{#                  <option value="PA">Pennsylvania</option>#}
{#                  <option value="RI">Rhode Island</option>#}
{#                  <option value="SC">South Carolina</option>#}
{#                  <option value="SD">South Dakota</option>#}
{#                  <option value="TN">Tennessee</option>#}
{#                  <option value="TX">Texas</option>#}
{#                  <option value="UT">Utah</option>#}
{#                  <option value="VT">Vermont</option>#}
{#                  <option value="VA">Virginia</option>#}
{#                  <option value="WA">Washington</option>#}
{#                  <option value="WV">West Virginia</option>#}
{#                  <option value="WI">Wisconsin</option>#}
{#                  <option value="WY">Wyoming</option>#}
{#                </select>#}
{#              </div>#}
            </div>
            <!-- Form Row 2 -->
            <div class="form-row">
              <div class="col-md-6 mb-3">
                <label class="sr-only">Bedrooms</label>
                <select name="bedrooms" class="form-control">
                  <option selected="true" disabled="disabled">Bedrooms (Any)</option>
                  {% for key,value in bedroom_choices.items  %}
                      <option value="{{ key }}" {% if key == values.bedrooms %}selected{% endif %}>{{ value }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="col-md-6 mb-3">
                <select name="price" class="form-control">
                  <option selected="true" disabled="disabled">Max Price (All)</option>
                  {% for key,value in price_choices.items %}
                      <option value="{{ key }}" {% if key == values.price %}selected{% endif %}>{{ value }}</option>
                  {% endfor %}
                </select>
              </div>
            </div>
            <button class="btn btn-secondary btn-block mt-4" type="submit">Submit form</button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="index.html">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item">
            <a href="listings.html">Browse Listings</a>
          </li>
          <li class="breadcrumb-item active"> Search Results</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Listings -->
    <section id="listings" class="py-4">
        <div class="container">
            <div class="row">
                {% if listings %}
                    {% for listing in listings %}
                        <div class="col-md-6 col-lg-4 mb-4">
                            <div class="card listing-preview">
                                <img class="card-img-top" src="{{ listing.photo_main.url }}" alt="">
                                <div class="card-img-overlay">
                                    <h2>
                                        <span class="badge badge-secondary text-white">Rs.{{ listing.price | intcomma }}</span>
                                    </h2>
                                </div>
                                <div class="card-body">
                                    <div class="listing-heading text-center">
                                        <h4 class="text-primary">{{ listing.title }}</h4>
                                        <p>
                                            <i class="fas fa-map-marker text-secondary"></i>
                                            {{ listing.address }}, {{ listing.city }}
                                        </p>
                                    </div>
                                    <hr>
                                    <div class="row py-2 text-secondary">
                                        <div class="col-6">
                                            <i class="fas fa-th-large"></i> Sqft: {{ listing.house_area }}</div>
                                        <div class="col-6">
                                            <i class="fas fa-car"></i> kitchens: {{ listing.kitchen }}</div>
                                    </div>
                                    <div class="row py-2 text-secondary">
                                        <div class="col-6">
                                            <i class="fas fa-bed"></i> Bedrooms: {{ listing.bedrooms }}</div>
                                        <div class="col-6">
                                            <i class="fas fa-bath"></i> Bathrooms: {{ listing.bathrooms }}</div>
                                    </div>
                                    <hr>
                                    <div class="row py-2 text-secondary">
                                        <div class="col-12">
                                            <i class="fas fa-user"></i>{{ listing.realtor.name }}</div>
                                    </div>
                                    <div class="row text-secondary pb-2">
                                        <div class="col-6">
                                            <i class="fas fa-clock"></i> {{ listing.list_date | timesince}}</div>
                                    </div>
                                    <hr>
                                    <a href="{% url 'listings:listing' listing.id %}" class="btn btn-primary btn-block">More Info</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="col-md-12">
                        <p>No Listings available</p>
                    </div>
                {% endif %}

            </div>
        </div>
    </section>

{% endblock %}